# Generated by Django 4.1.1 on 2022-09-28 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formato931',
            name='ordenregistro',
        ),
        migrations.AddField(
            model_name='ordenregistro',
            name='formatof931',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='export_lsd.formato931'),
        ),
    ]
