# Generated by Django 4.1.1 on 2022-09-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0002_remove_formato931_ordenregistro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenregistro',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
