# Generated by Django 4.1.1 on 2022-10-10 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0003_alter_ordenregistro_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre')),
                ('leg', models.PositiveSmallIntegerField(unique=True)),
                ('cuil', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
            ],
        ),
    ]
