# Generated by Django 4.1.1 on 2022-10-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0004_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='empresa',
            field=models.ManyToManyField(to='export_lsd.empresa'),
        ),
    ]
