# Generated by Django 4.1.1 on 2022-10-10 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0005_empleado_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='leg',
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg', models.PositiveSmallIntegerField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='export_lsd.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='export_lsd.empresa')),
            ],
        ),
    ]
