# Generated by Django 4.1.1 on 2022-10-10 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0006_remove_empleado_leg_empresaempleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='empresa',
        ),
    ]
