# Generated by Django 4.1.1 on 2022-10-14 12:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0008_empresa_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='empleado',
        ),
        migrations.AddField(
            model_name='empleado',
            name='cuil',
            field=models.CharField(default=1, max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='export_lsd.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre'),
        ),
    ]
