# Generated by Django 4.1.1 on 2022-10-14 15:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('export_lsd', '0010_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basicexportconfig',
            unique_together={('user', 'name')},
        ),
    ]
