# Generated by Django 4.1.1 on 2022-10-15 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0011_alter_basicexportconfig_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cuil',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10000000000), django.core.validators.MaxValueValidator(99999999999)]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cuit',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10000000000), django.core.validators.MaxValueValidator(99999999999)]),
        ),
    ]
