# Generated by Django 4.1.1 on 2022-10-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0014_liquidacion_presentacion_delete_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacion',
            name='employees',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presentacion',
            name='remuneracion',
            field=models.FloatField(default=0.0),
        ),
    ]
