# Generated by Django 4.1.1 on 2022-10-24 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('export_lsd', '0015_presentacion_employees_presentacion_remuneracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
