# Generated by Django 4.1.1 on 2022-10-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0017_liquidacion_remuneracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
