# Generated by Django 4.1.1 on 2022-10-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0018_alter_liquidacion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
