# Generated by Django 4.1.1 on 2022-10-25 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0020_liquidacion_nroliq'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liquidacion',
            unique_together={('nroLiq', 'presentacion')},
        ),
    ]
