# Generated by Django 4.1.1 on 2022-10-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0021_alter_liquidacion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion',
            name='employees',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='remuneracion',
            field=models.FloatField(default=0.0),
        ),
    ]
