# Generated by Django 4.1.1 on 2022-10-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0022_alter_liquidacion_employees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacion',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='liquidacion',
            name='remuneracion',
        ),
        migrations.RemoveField(
            model_name='presentacion',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='presentacion',
            name='remuneracion',
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='payday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
