# Generated by Django 4.1.1 on 2022-10-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0023_remove_liquidacion_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion',
            name='payday',
            field=models.DateField(),
        ),
    ]
