# Generated by Django 4.1.1 on 2022-10-25 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0024_alter_liquidacion_payday'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacion',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ConceptoLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=10)),
                ('cantidad', models.PositiveSmallIntegerField(default=0)),
                ('importe', models.FloatField(default=0)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='export_lsd.empleado')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='export_lsd.liquidacion')),
            ],
            options={
                'verbose_name_plural': 'ConceptoLiquidaciones',
            },
        ),
    ]
