# Generated by Django 4.1.1 on 2022-10-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0025_presentacion_closed_conceptoliquidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='employees',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='no_remunerativos',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='remunerativos',
            field=models.FloatField(default=0.0),
        ),
    ]
