# Generated by Django 4.1.1 on 2022-11-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0030_empleado_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptoliquidacion',
            name='tipo',
            field=models.CharField(default='Rem', max_length=3, verbose_name='Tipo de Concepto'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='area',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Área de Trabajo'),
        ),
    ]
