# Generated by Django 4.1.1 on 2022-11-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_lsd', '0032_alter_conceptoliquidacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='tipo_liq',
            field=models.CharField(choices=[('M', 'Mes'), ('Q', 'Quincena'),
                                            ('D', 'Días'), ('H', 'Horas')],
                                   default='M', max_length=1, verbose_name='Tipo Liq.'),
        ),
    ]
