# Generated by Django 4.1.1 on 2022-09-27 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('fromm', models.PositiveSmallIntegerField()),
                ('long', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('AL', 'Alfanumérico'), ('NU', 'Numérico')], default='AL', max_length=2)),
                ('description', models.TextField()),
                ('tiporegistro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.tiporegistro')),
            ],
        ),
        migrations.DeleteModel(
            name='OrdenRegistros',
        ),
    ]
