# Generated by Django 4.1.1 on 2022-09-27 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_ordenregistro_delete_ordenregistros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiporegistro',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='tiporegistro',
            old_name='orden',
            new_name='order',
        ),
    ]
