# Generated by Django 4.1.1 on 2022-09-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_tiporegistro_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenregistro',
            options={'ordering': ['tiporegistro__order', 'fromm']},
        ),
    ]
