# Generated by Django 4.1.1 on 2022-09-27 21:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_alter_ordenregistro_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Razon Social')),
                ('cuit', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
            ],
        ),
        migrations.AlterField(
            model_name='ordenregistro',
            name='type',
            field=models.CharField(choices=[('AL', 'Alfabético'), ('AN', 'Alfanumérico'), ('NU', 'Numérico')], default='AN', max_length=2),
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees', models.PositiveSmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.empresa')),
            ],
        ),
    ]
